version: '3.7'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - '-c'
      - sleep 1d
#      - service supervisor start && supervisorctl stop docker_test && sleep 1d
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    build: ./db
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data/
#      - '${DOCKER_COMPOSE_PROJECTS_PATH}/docker_test/db/psql:/var/lib/postgresql/data/'
#    ports:
#      - 54321:5432/tcp
    environment:
      - POSTGRES_USER=docker_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=docker_test_db_p
    restart: always

volumes:
  db: