# Generated by Django 3.1.1 on 2020-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='solved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
