# Generated by Django 3.1.1 on 2020-11-05 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0006_auto_20201105_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AddField(
            model_name='person',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last activity'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Is done'),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_notes', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Middle'), (3, 'Above the average'), (4, 'High'), (5, 'Highest')], verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='note',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='read_notes', to=settings.AUTH_USER_MODEL, verbose_name='Readers'),
        ),
        migrations.AlterField(
            model_name='note',
            name='solved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Solved at'),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
